name: Release Workflow

env:
  renpy_version: "8.1.0"
  game_version: "1.0"
  itch_project_name: akibaokapi/after-passion
  build_name: AfterPassion
  android_build_name: games.akiba.afterpassion

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Cache renpy
        id: cache-renpy
        uses: actions/cache@v3
        env:
          cache-name: cache-renpy
        with:
          path: |
            ~/.renutil
            !~/.renutil/**/*.keystore
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('renconstruct.toml') }}
      - name: Build After Passion
        run: |
          unset ANDROID_NDK_HOME
          wget -qO- https://github.com/kobaltcore/renkit/releases/download/v3.2.0/renkit-linux-amd64.tar.gz | sudo tar xz -C /usr/local/bin
          [ ! -d ~/.renutil ] && renutil install -v ${{ env.renpy_version }}
          mkdir -p ~/.renutil/${{ env.renpy_version }}/rapt/project/app/
          echo -n '${{ secrets.ANDROID_KEYSTORE }}' | base64 --decode > ~/.renutil/${{ env.renpy_version }}/rapt/project/app/android.keystore
          renconstruct build -i . -o .artifacts/ -c renconstruct.toml
          rm ~/.renutil/${{ env.renpy_version }}/rapt/project/app/android.keystore
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Publish builds to itch.io
        run: |
          ls -l .artifacts
          butler push .artifacts/${{ env.build_name }}-${{ env.game_version }}-pc.zip ${{ env.itch_project_name }}:win-linux --userversion ${{ env.game_version }}
          sleep 30
          butler push .artifacts/${{ env.build_name }}-${{ env.game_version }}-mac.zip ${{ env.itch_project_name }}:mac --userversion ${{ env.game_version }}
          sleep 30
          butler push .artifacts/${{ env.android_build_name }}-release.apk ${{ env.itch_project_name }}:android --userversion ${{ env.game_version }}
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
